-- Write a query to create a table called artists in 
-- src/artists.sql. It should have the following fields:

-- A artist_id field that serves as a primary key for the table.

-- A artist_name field with a varying character datatype and 
-- a character limit of 255 characters.

-- A genre_name field with a varying character datatype and 
-- a character limit of 100 characters.

create table artists 
(
    artist_id 
    INTEGER 
    PRIMARY KEY generated by default AS identity,
    
    artist_name 
    varchar(255) 
    not null,

    genre_name 
    varchar(100)
)