-- INSTRUCTIONS:
-- Write a query to create a table called concerts in 
-- src/concerts.sql. It should have the following fields:

-- A concert_id field that serves as a primary key for the table.

-- A concert_name field with a varying character datatype, 
-- a character limit of 255 characters.

-- A concert_date field with a date datatype.

-- SYNTAX:
-- CREATE TABLE table_name (
--    column_name data_type  column_constraint [ , ]
-- )

create table concerts(
    concert_id 
    INTEGER 
    primary key generated by default as identity,
    
    concert_name 
    varchar(255),
    
    concert_date 
    date
)