-- INSTRUCTIONS:

-- Write a query to create a table called songs in src/songs.sql. 
-- It should have the following fields:

-- A song_id field that serves as a primary key for the table.

-- A song_name field with a varying character datatype, 
-- a character limit of 100 characters, and a default string value of no song title.

-- A album_name field with a varying character datatype, a character 
-- limit of 100 characters, and a default string value of no 
-- album title.

-- Create a one-to-many relationship between the artists and songs tables (i.e., an artist can be associated with many songs). To do this, reference the artist_id from the artists table as a foreign key called artist in the songs table. Set a constraint on this foreign key so that it cannot be null.


create table songs 
(
    song_id 
    INTEGER 
    primary key generated by default as identity,

    song_name 
    varchar(100) 
    default 'no song title',

    album_name 
    varchar(100) 
    default 'no album title',

    artist 
    INTEGER 
    references artists(artist_id)  
    not null
)
